<?php
/**
 * Cmsbox.fr Magento 2 Payment module (https://www.cmsbox.fr)
 *
 * Copyright (c) 2017 Cmsbox.fr (https://www.cmsbox.fr)
 * Author: David Fiaty | contact@cmsbox.fr
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */

 ?>
    <div class="credit-card">
        <div class="form-header">
            <h4 class="title"><?= $block->escapeHtml(__('Card Details')); ?></h4>
        </div>
        <div class="form-body">
            <!-- Card Number -->
            <input type="number" name="card_data[number]" class="card-number" placeholder="<?= $block->escapeHtml(__('Card Number')); ?>" title="<?= $block->escapeHtml(__('Card Number')) ?>">

            <!-- Date Field -->
            <div class="date-field">
                <div class="month">
                    <select name="card_data[month]">
                        <?php foreach ($block->months as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $block->escapeHtml($k) ?>">
                                <?= $block->escapeHtml($v) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="year">
                    <select name="card_data[year]">
                        <?php foreach ($block->years as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $block->escapeHtml($k) ?>">
                                <?= $block->escapeHtml($v) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <!-- Card Verification Field -->
            <div class="card-verification">
                <div class="cvv-input">
                    <input type="text" name="card_data[cvv]" placeholder="<?= $block->escapeHtml(__('CVV')) ?>">
                </div>
            </div>
        </div>
    </div>
