<?php
/**
 * Cmsbox.fr Magento 2 Payment module (https://www.cmsbox.fr)
 *
 * Copyright (c) 2017 Cmsbox.fr (https://www.cmsbox.fr)
 * Author: David Fiaty | contact@cmsbox.fr
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */

// Get the block data
$isAdmin = $block->getData('is_admin');
$moduleName = $block->getData('module_name');
$methodId = ($block->getMethodCode()) ? $block->getMethodCode() : $block->getData('method_id');
$templateName = $block->getData('template_name');
$formCssFile = $this->assetRepository->createAsset($moduleName . '::css/payment_form/' . $templateName . '.css', ['area' => 'adminhtml'])->getUrl();
?>
<style>
    @import url(<?= $formCssFile ?>);
</style>

<?php if ($isAdmin) : ?>
    <fieldset class="admin__fieldset payment-method <?= /* @noEscape */ $methodId ?>" id="payment_form_<?= /* @noEscape */ $methodId ?>" style="display: none;">
<?php endif; ?>

<div class="card-form-container">
    <div class="checkout-header">
        <h1 class="checkout-title"><?= $block->escapeHtml(__('Card details')); ?></h1>
    </div>
    <p>
        <input type="text" 
               class="checkout-input checkout-name"
               placeholder="<?= $block->escapeHtml(__('Card holder name')); ?>"
               name="card_data[name]"
               >
        <input type="text"
               class="checkout-input checkout-exp"
               placeholder="<?= $block->escapeHtml(__('MM')); ?>"
               name="card_data[month]"
               data-validate="{'required-entry':true, 'validate-card-date':true}"
               >
        <input type="text"
               class="checkout-input checkout-exp"
               placeholder="<?= $block->escapeHtml(__('YY')); ?>"
               name="card_data[year]"
               data-validate="{'required-entry':true, 'validate-card-year':true}"
               >
    </p>
    <p>
        <input type="text"
               class="checkout-input checkout-card"
               placeholder="<?= $block->escapeHtml(__('Card number')); ?>"
               name="card_data[number]"
               data-validate="{'required-entry':true, 'validate-cc-number':true}"
               title="<?= $block->escapeHtml(__('Card number')) ?>"
               >
        <?php if ($this->config->params[$methodId]['cvv_check_customer']): ?>
        <input type="text"
               class="checkout-input checkout-cvc"
               placeholder="<?= $block->escapeHtml(__('CVV')); ?>"
               >
        <?php endif; ?>
    </p>
</div>

<?php if ($isAdmin) : ?>
    </fieldset>
<?php endif; ?>

<script>
    //<![CDATA[
    require(
        [
            'jquery',
            'uiComponent',
            'domReady!',
            'Magento_Payment/js/model/credit-card-validation/validator',
            'mage/validation'
        ], function($, Component) {
            return Component.extend({
                validateForm: function (form) {
                    return $(form).validation() && $(form).validation('isValid');
                }
            });
        });
    //]]>
</script>