<!--
/**
 * Cmsbox.fr Magento 2 Payment module (https://www.cmsbox.fr)
 *
 * Copyright (c) 2017 Cmsbox.fr (https://www.cmsbox.fr)
 * Author: David Fiaty | contact@cmsbox.fr
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */
-->

<div class="payment-method" data-bind="css: {'_active': (getCode() == isChecked())}">
    <div class="payment-method-title field choice">
        <input type="radio" name="payment[method]" class="radio" data-bind="attr: {'id': getCode()}, value: getCode(), checked: isChecked, click: selectPaymentMethod, visible: isRadioButtonVisible()" />
        <label class="label" data-bind="attr: {'for': getCode()}">
            <span data-bind="text: getTitle()"></span>
        </label>
    </div>

    <div class="payment-method-content">
        <div class="message" style="display: none"></div>
        <div>
            <form class="form" data-bind="attr: {id: targetForm, action: config.api_url}" method="POST" novalidate="novalidate" style="display:none">
                <input name="Data" data-bind="attr: {value: config.request_data.params}">
                <input name="InterfaceVersion" data-bind="attr: {value: config.interface_version_charge}">
                <input name="Seal" data-bind="attr: {value: config.request_data.seal}">
            </form>
            <iframe id="targetIframe" data-bind="attr: {visible: createIframe(), width: config.iframe_width, height: config.iframe_height, frameborder: config.iframe_border}"></iframe>
        </div>

        <div class="payment-method-billing-address">
            <!-- ko foreach: $parent.getRegion(getBillingAddressFormName()) -->
            <!-- ko template: getTemplate() -->
            <!-- /ko -->
            <!--/ko-->
        </div>

        <div class="checkout-agreements-block">
            <!-- ko foreach: $parent.getRegion('before-place-order') -->
            <!-- ko template: getTemplate() -->
            <!-- /ko -->
            <!--/ko-->
        </div>
    </div>
</div>